---
- name: Provision TeamCity
  hosts: all
  become: true

  tasks:
    - name: Install Java
      become: true
      dnf:
        name: java-11-openjdk
        state: present
      tags:
        - java

    - name: Download TeamCity
      get_url:
        url: "https://download.jetbrains.com/teamcity/TeamCity-2023.05.4.tar.gz"
        dest: "/tmp"
      tags:
        - teamcity

    - name: Extract TeamCity
      become: true
      ansible.builtin.unarchive:
        src: "/tmp/TeamCity-2023.05.4.tar.gz"
        dest: "/opt"
        remote_src: true
      tags:
        - teamcity

    - name: Set Permissions
      become: true
      ansible.builtin.file:
        path: "/opt/TeamCity"
        owner: lesia
        group: lesia
        recurse: yes
      tags:
        - teamcity

    - name: Start TeamCity
      become: true
      ansible.builtin.shell:
        cmd: "/opt/TeamCity/bin/teamcity-server.sh start"
      tags:
        - teamcity
